ArjunaJTA/jee_transactional_app/src/main/java/org/jboss/narayana/quickstarts/jsf/CustomerManagerManagedBean.java
/*
 * JBoss, Home of Professional Open Source
 * Copyright 2011, Red Hat, Inc. and/or its affiliates,
 * and individual contributors as indicated by the @author tags.
 * See the copyright.txt in the distribution for a
 * full listing of individual contributors.
 * This copyrighted material is made available to anyone wishing to use,
 * modify, copy, or redistribute it subject to the terms and conditions
 * of the GNU Lesser General Public License, v. 2.1.
 * This program is distributed in the hope that it will be useful, but WITHOUT A
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
 * You should have received a copy of the GNU Lesser General Public License,
 * v.2.1 along with this distribution; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA  02110-1301, USA.
 *
 * (C) 2011,
 * @author JBoss, by Red Hat.
 */
package org.jboss.narayana.quickstarts.jsf;

import java.util.List;

import javax.faces.bean.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.naming.NamingException;
import javax.transaction.HeuristicMixedException;
import javax.transaction.HeuristicRollbackException;
import javax.transaction.NotSupportedException;
import javax.transaction.RollbackException;
import javax.transaction.SystemException;
import javax.transaction.UserTransaction;

import org.jboss.logging.Logger;
import org.jboss.narayana.quickstarts.ejb.CustomerManagerEJB;
import org.jboss.narayana.quickstarts.jpa.Customer;

@Named("customerManager")
@RequestScoped
public class CustomerManagerManagedBean implements CustomerManager {
	private Logger logger = Logger.getLogger(CustomerManagerManagedBean.class
			.getName());

	@Inject
	private CustomerManagerEJB customerManagerEJB;

	@Inject
	private UserTransaction userTransaction;

	public List<Customer> getCustomers() throws SecurityException,
			IllegalStateException, NamingException, NotSupportedException,
			SystemException, RollbackException, HeuristicMixedException,
			HeuristicRollbackException {
		logger.debug("Getting customers");
		return customerManagerEJB.listCustomers();
	}

	public String addCustomer(String name) {
		logger.debug("Adding customer: " + name);
		try {
			userTransaction.begin();
			logger.debug("Creating customer");
			customerManagerEJB.createCustomer(name);
			userTransaction.commit();
			logger.debug("Created customer");
			return "customerAdded";
		} catch (Exception e) {
			logger.debug("Caught a duplicate", e);
			// Transaction will be marked rollback only anyway utx.rollback();
			return "customerDuplicate";
		}
	}

	public int getCustomerCount() throws Exception {
		logger.debug("Getting count");
		int count = customerManagerEJB.getCustomerCount();
		return count;
	}
}

ArjunaJTA/jee_transactional_app/src/main/webapp/addCustomer.xhtml
<!-- JBoss, Home of Professional Open Source Copyright 2009, Red Hat Middleware 
		LLC, and individual contributors as indicated by the @author tags. See the 
		copyright.txt in the distribution for a full listing of individual contributors. 
		This copyrighted material is made available to anyone wishing to use, modify, 
		copy, or redistribute it subject to the terms and conditions of the GNU Lesser 
		General Public License, v. 2.1. This program is distributed in the hope that 
		it will be useful, but WITHOUT A WARRANTY; without even the implied warranty 
		of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser 
		General Public License for more details. You should have received a copy 
		of the GNU Lesser General Public License, v.2.1 along with this distribution; 
		if not, write to the Free Software Foundation, Inc., 51 Franklin Street, 
		Fifth Floor, Boston, MA 02110-1301, USA. (C) 2009 -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">

<ui:composition template="template.xhtml">
	<ui:define name="content">
		<h:messages />
		<h:form id="addCustomerForm">
			<h:panelGrid columns="3">
				<h:outputLabel for="name">Name:</h:outputLabel>
				<h:inputText value="#{name}" />
				<h:commandButton id="add" value="Add"
					action="#{customerManager.addCustomer(name)}">
				</h:commandButton>
			</h:panelGrid>
		</h:form>
		<h:link outcome="/customers.xhtml">List customers</h:link>
		<h:link outcome="/count.xhtml">List count</h:link>
	</ui:define>
</ui:composition>
</html>

ArjunaJTA/jee_transactional_app/src/main/webapp/count.xhtml
<!-- JBoss, Home of Professional Open Source Copyright 2009, Red Hat Middleware 
		LLC, and individual contributors as indicated by the @author tags. See the 
		copyright.txt in the distribution for a full listing of individual contributors. 
		This copyrighted material is made available to anyone wishing to use, modify, 
		copy, or redistribute it subject to the terms and conditions of the GNU Lesser 
		General Public License, v. 2.1. This program is distributed in the hope that 
		it will be useful, but WITHOUT A WARRANTY; without even the implied warranty 
		of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser 
		General Public License for more details. You should have received a copy 
		of the GNU Lesser General Public License, v.2.1 along with this distribution; 
		if not, write to the Free Software Foundation, Inc., 51 Franklin Street, 
		Fifth Floor, Boston, MA 02110-1301, USA. (C) 2009 -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">

<ui:composition template="template.xhtml">
	<ui:define name="content">
		<Count />
		<h1>Customer Count</h1>
		<h:outputText value="Count this run: #{customerManager.customerCount}" />
		<a href="javascript:history.back(-1)">Go Back</a>
	</ui:define>
</ui:composition>
</html>

ArjunaJTA/jee_transactional_app/src/main/webapp/customers.xhtml
<!-- JBoss, Home of Professional Open Source Copyright 2009, Red Hat Middleware 
		LLC, and individual contributors as indicated by the @author tags. See the 
		copyright.txt in the distribution for a full listing of individual contributors. 
		This copyrighted material is made available to anyone wishing to use, modify, 
		copy, or redistribute it subject to the terms and conditions of the GNU Lesser 
		General Public License, v. 2.1. This program is distributed in the hope that 
		it will be useful, but WITHOUT A WARRANTY; without even the implied warranty 
		of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser 
		General Public License for more details. You should have received a copy 
		of the GNU Lesser General Public License, v.2.1 along with this distribution; 
		if not, write to the Free Software Foundation, Inc., 51 Franklin Street, 
		Fifth Floor, Boston, MA 02110-1301, USA. (C) 2009 -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">

<ui:composition template="template.xhtml">
	<ui:define name="content">
		<h:messages />
		<h1>List of customers</h1>
		<h:dataTable value="#{customerManager.customers}" var="u">
			<h:column>
				<f:facet name="header">
               Name
            </f:facet>
				<h:outputText value="#{u.name}" />
			</h:column>
			<h:column>
				<f:facet name="header">
               Id
            </f:facet>
				<h:outputText value="#{u.id}" />
			</h:column>
		</h:dataTable>
		<a href="javascript:history.back(-1)">Go Back</a>
	</ui:define>
</ui:composition>
</html>

ArjunaJTA/jee_transactional_app/src/main/webapp/duplicate.xhtml
<!-- JBoss, Home of Professional Open Source Copyright 2009, Red Hat Middleware 
		LLC, and individual contributors as indicated by the @author tags. See the 
		copyright.txt in the distribution for a full listing of individual contributors. 
		This copyrighted material is made available to anyone wishing to use, modify, 
		copy, or redistribute it subject to the terms and conditions of the GNU Lesser 
		General Public License, v. 2.1. This program is distributed in the hope that 
		it will be useful, but WITHOUT A WARRANTY; without even the implied warranty 
		of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser 
		General Public License for more details. You should have received a copy 
		of the GNU Lesser General Public License, v.2.1 along with this distribution; 
		if not, write to the Free Software Foundation, Inc., 51 Franklin Street, 
		Fifth Floor, Boston, MA 02110-1301, USA. (C) 2009 -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">

<ui:composition template="template.xhtml">
	<ui:define name="content">
		<Count />
		<h1>Customer Already Existed</h1>
		<h:outputText value="Customer already existed: #{name}" />
		<a href="javascript:history.back(-1)">Go Back</a>
	</ui:define>
</ui:composition>
</html>

ArjunaJTA/jee_transactional_app/src/main/webapp/template.xhtml
<!-- JBoss, Home of Professional Open Source Copyright 2009, Red Hat Middleware 
		LLC, and individual contributors as indicated by the @author tags. See the 
		copyright.txt in the distribution for a full listing of individual contributors. 
		This copyrighted material is made available to anyone wishing to use, modify, 
		copy, or redistribute it subject to the terms and conditions of the GNU Lesser 
		General Public License, v. 2.1. This program is distributed in the hope that 
		it will be useful, but WITHOUT A WARRANTY; without even the implied warranty 
		of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser 
		General Public License for more details. You should have received a copy 
		of the GNU Lesser General Public License, v.2.1 along with this distribution; 
		if not, write to the Free Software Foundation, Inc., 51 Franklin Street, 
		Fifth Floor, Boston, MA 02110-1301, USA. (C) 2009 -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">

<!-- The template for our app, defines some regions and imports styles -->

<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Customer Database</title>
<ui:insert name="head" />
</head>

<body>

	<h1>Customer Database</h1>
	<div id="container">
		<div id="header"></div>

		<div id="sidebar"></div>

		<div id="content">
			<ui:insert name="content" />
		</div>

		<br style="clear: both" />
	</div>

</body>
</html>
